### ISSUE TITLE
integer overflow in src/file.c

### ISSUE THREAD

**Issue by greenbuggedeyedmonster** [Aransentin/RT-Engine#1]
you has integer overflow in da src/file.c. when da length of da file is UINT_MAX, ya will allocate too little memories (UINT_MAX + 1 = 0) and read too many data into small buffer, so .. bang!

u.

**Comment by Aransentin** [comment]
I'll fix it on the next commit; though size_t is 8 bytes (on a 64-bit machine), triggering an overflow would require a file that's 16 exabytes large.

On a 32-bit machine, ftell() doesn't support files larger than 2GiB anyway; you'd need to use fseeko() or something like that.
